// <auto-generated />
namespace Sports_News_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingBaseDbSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingBaseDbSet));
        
        string IMigrationMetadata.Id
        {
            get { return "202004012315034_AddingBaseDbSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
